dist: trusty
sudo: false
language: cpp

env:
  global:
  # For coverity
   - secure: "gfnlLwBrk8D0GsqjjxMCLMV7vLYlJX31r7gzm90FQB0R8EBZA8c87V82mtT/D9sRe6DPk4X42/rE9ewdkvQnC4iHMKZiQdFVn/MoBi4e8Juy9cWrAPBjvCosyjuCgFrfORlES7A1GdSuu54P5dTotXEJjaTO0S6q0cQgL7/uDfLhFz3kuIygDoi4oT12PlAfJGqXXG4aphN4DmeM5wEAEuAIjUAva354TzqT+VN7t6KMYhL7N68qoZ10Mm1XZZevXDVmjVf9zIvZsN53SvUoK1C7drWQC/O+O9dVAYIVD4LWqXXRF16PsmbF+geDQ/vdDs90nlbi4ZE4FiLvbhZKgPRw/61a2L/COdgVp0fcmwrXJTjGYt+61WtEu+9y9bPR+w9jJsR68lg+G3XCpVhUQv2PTEXrfSR5K+4RLkJRd9ML//ZficWuf1DyG2BVHiyz+/WF7HbCJx3rh9nL/c0JufCn+7WLKo7iBaBxuOrCdNO6P/SrNvmQMa/Ubu2IelI6+ieellb0pZnMyr3OcqXnrMtzJtkcyV/pG6UeBM4VKfkh9pq1xVPycOwkfVUvR87bvwkjdxPwQUt0koWWT0TwVJBcsAkFz6ODK8p0gMJeUfd716ze/R2tjJ08OnDtac5VphI63DEG+/NOzPzp9rfPrNQMNSWOQXM3Rly0Ns++L8A="

compiler:
  - clang
  - gcc

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - libxerces-c-dev
  coverity_scan:
    project:
      name: "asmaloney/libE57Format"
      description: "Library for reading & writing the E57 file format (fork of E57RefImpl) "
    notification_email: asmaloney@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .."
    build_command: "make -j2"
    branch_pattern: coverity_scan
    
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" != 1 ]]; then
      gcc -v && g++ -v && cmake --version;
      make -j2;
    fi