dist: trusty
sudo: false
language: cpp

env:
  global:
  # For coverity
   - secure: "NuVS294kS07UsIj+R9Ae0KTCeOn4s9SgAykye0Pu+DKxu8LV6GeU4ceTbdZHnfZsqPy8KGwkL09MEj/j9JYtP3+dO0vTFTFqOBj4kVi7YyhHYr2WazdvC5wg+imPdeU2BshBs0kD5lCp/UqnQXo+/02xB6/bKP4kjvuQU2aqXyoaQ72a1cqtO/w2o1r8Gr4JwqizPnuFdEJVknSJsraGaEDGpQXB8b5jWXRzwIKOsAxOy7Bcucd7GqvignAefZzDq/ivNVvdNcqBCztu5TqY04yW6wKvv+qEOguEr5oH/FmQkTyckN8MMvXnGXiiRUXH0j6M+R1xnYasqdCiEcXkglEQ5Epy/KJguGmhOhURY54jkeJip1H5pcRIYuGE9hVrRCmBUW6w61Iqt2wduMLqqetZ7GClQ5jM8sqwR/UfP7gQqwOoJn3ZolOwX/McotqXpzItGOUQyPiQoPsEKagmXjHMNe2OBKHeRq5ayDE8r5TfqmSDxtWzb1HQpLFZoO7N8X01A2cAs+L1HLoQkFUsv25PV8TQb3Q3aBr1Ad9v4g1hs1p1llF2jZ47gwIHmNHvO9zVdDZ8hgJmeqqeetbT1gumnJ6hQiNu46M9eDrWxEWLJiLl5KZRp7VZMwzh3xqawSd+TKhvs70DK3cPLgjhRUMC2vo8euT8WjLPTNbddws="

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libxerces-c-dev
  coverity_scan:
    project:
      name: "asmaloney/libE57Format"
      description: "Library for reading & writing the E57 file format (fork of E57RefImpl) "
    notification_email: asmaloney@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .."
    build_command: "make -j2"
    branch_pattern: coverity_scan
    
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" != 1 ]]; then
      gcc -v && g++ -v && cmake --version
      make -j2
    fi